### ISSUE TITLE
Неэффективное определение наличия юзера

### ISSUE THREAD

**Issue by konyahin** [Nimoto/javatanks#3]
https://github.com/Nimoto/javatanks/blob/9ea2928a044eb22597d9eba631561cf6cc403378/src/main/java/ru/nimoto/tanks/controllers/UserController.java#L15
Тут для поиска юзера по имени приходится каждый раз обходить всех имеющихся пользователей. Это не оптимально. В качестве решения предлагаю использовать HashSet для username и проверять наличие через contains.

**Comment by Nimoto** [comment]
неактуально
